run:
  timeout: 3m
linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - errcheck
    - gofumpt
    - gocritic
    - revive
issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
